name: synnerdata-api-b

services:
  postgres:
    image: postgres:17-alpine
    container_name: synnerdata-api-b
    environment:
      POSTGRES_DB: synnerdata-api-b
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - synnerdata-api-b_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: synnerdata-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  synnerdata-api-b_postgres_data:
