name: Test

on:
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: CI/CD

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: synnerdata_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/synnerdata_test
      SMTP_HOST: localhost
      SMTP_PORT: 1025
      SUPER_ADMIN_EMAILS: superadmin@test.com
      ADMIN_EMAILS: admin@test.com
      SKIP_INTEGRATION_TESTS: "true"
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      PAGARME_BASE_URL: ${{ secrets.PAGARME_BASE_URL }}
      PAGARME_SECRET_KEY: ${{ secrets.PAGARME_SECRET_KEY }}
      PAGARME_PUBLIC_KEY: ${{ secrets.PAGARME_PUBLIC_KEY }}
      PAGARME_WEBHOOK_USERNAME: ${{ secrets.PAGARME_WEBHOOK_USERNAME }}
      PAGARME_WEBHOOK_PASSWORD: ${{ secrets.PAGARME_WEBHOOK_PASSWORD }}
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      PII_ENCRYPTION_KEY: ${{ secrets.PII_ENCRYPTION_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Setup database
        run: bun run db:push

      - name: Seed database
        run: bun run db:seed

      - name: Run tests
        run: bun run test
